### ISSUE TITLE
greek-nt.xml:  2 Peter is missing.

### ISSUE THREAD

**Issue by jonathanrobie** [proiel/proiel-treebank#10] opened 2017-12-26 22:43 UTC
2 Peter seems to be missing in greek-nt.xml.

**Comment by hanneme** [comment] 2017-12-26 22:47
In response to this and the other issues you opened about missing bits of GNT: They are missing because they are not yet reviewed, i.e. they are annotated, but not yet proofread, and therefore not released.

**Comment by mlj** [comment] 2017-12-26 22:49
Hi @jonathanrobie , thanks for this!

There are several gaps in the text where annotation is still missing. On our annotation system 1 Peter, 2 Peter, 1 John, 2 John, 3 John and Jude are all listed as having gaps in them. (There are similar gaps in the other published texts in PROIEL.)

We really ought to bundle an up-to-date list with the treebank so this is clear upfront.

**Comment by mlj** [comment] 2017-12-26 22:55
Closing as duplicate of #11. Please continue discussion there.

**Closed by mlj** 2017-12-26 22:56 UTC
