### ISSUE TITLE
greek-nt.xml: 1 Peter is truncated after 1 Peter 3:4

### ISSUE THREAD

**Issue by jonathanrobie** [proiel/proiel-treebank#9] opened 2017-12-26 22:42 UTC
In greek-nt.xml, 1 Peter ends with 1 Peter 3:4.  The last two chapters are missing, and so is everything after verse 4 in the third chapter.

**Comment by mlj** [comment] 2017-12-26 22:56
Closing as duplicate of #11. Please continue discussion there.

**Closed by mlj** 2017-12-26 22:56 UTC
