### ISSUE TITLE
greek-nt.xml:  Most of 3 John is missing, only part of 3 John 1:11 is there

### ISSUE THREAD

**Issue by jonathanrobie** [proiel/proiel-treebank#7] opened 2017-12-26 21:18 UTC
Most of 3 John is missing, only part of 3 John 1:11 is there.  Here are the entire contents of that book:

```xml
    <div id="312">
      <title>3 John 1</title>
      <sentence id="32875" status="reviewed" presentation-after=" ">
        <token id="491353" form="ὁ" citation-part="3JOHN 1.11" lemma="ὁ" part-of-speech="S-" morphology="-s---mn--i" head-id="491354" relation="aux" presentation-after=" "/>
        <token id="491354" form="κακοποιῶν" citation-part="3JOHN 1.11" lemma="ἀγαθοποιέω" part-of-speech="V-" morphology="-sppamn--i" head-id="491356" relation="sub" presentation-after=" "/>
        <token id="491355" form="οὐχ" citation-part="3JOHN 1.11" lemma="οὐ" part-of-speech="Df" morphology="---------n" head-id="491356" relation="aux" presentation-after=" "/>
        <token id="491356" form="ἑώρακεν" citation-part="3JOHN 1.11" lemma="ὁράω" part-of-speech="V-" morphology="3sria----i" relation="pred" presentation-after=" "/>
        <token id="491357" form="τὸν" citation-part="3JOHN 1.11" lemma="ὁ" part-of-speech="S-" morphology="-s---ma--i" head-id="491358" relation="aux" presentation-after=" "/>
        <token id="491358" form="θεόν" citation-part="3JOHN 1.11" lemma="θεός" part-of-speech="Nb" morphology="-s---ma--i" head-id="491356" relation="obj" presentation-after="."/>
      </sentence>
    </div>
```

**Comment by mlj** [comment] 2017-12-26 22:56
Closing as duplicate of #11. Please continue discussion there.

**Closed by mlj** 2017-12-26 22:56 UTC
