### ISSUE TITLE
greek-nt.xml: Jude contains only Jude 1:22-Jude 1:23

### ISSUE THREAD

**Issue by jonathanrobie** [proiel/proiel-treebank#6] opened 2017-12-26 21:12 UTC
In `greek-nt.xml`, Jude contains only Jude 1:22-Jude 1:23.

```xml
    <div id="313">
      <title>Jude 1</title>
      <sentence id="32923" status="reviewed">
        <token id="762576" form="καὶ" citation-part="JUDE 1.22" lemma="καί" part-of-speech="C-" morphology="---------n" head-id="762579" relation="aux" presentation-after=" "/>
        <token id="762577" form="οὓς" citation-part="JUDE 1.22" lemma="ὁ" part-of-speech="Pp" morphology="3p---ma--i" head-id="762579" relation="obj" presentation-after=" "/>
        <token id="762578" form="μὲν" citation-part="JUDE 1.22" lemma="μέν" part-of-speech="Df" morphology="---------n" head-id="762579" relation="aux" presentation-after=" "/>
        <token id="762579" form="ἐλέγχετε" citation-part="JUDE 1.22" lemma="ἐλέγχω" part-of-speech="V-" morphology="2ppma----i" relation="pred" presentation-after=" "/>
        <token id="762580" form="διακρινομένους" citation-part="JUDE 1.22" lemma="διακρίνω" part-of-speech="V-" morphology="-pppmma--i" head-id="762579" relation="xadv" presentation-after=", ">
          <slash target-id="762577" relation="xsub"/>
        </token>
      </sentence>
      <sentence id="57047" status="reviewed">
        <token id="762581" form="οὓς" citation-part="JUDE 1.23" lemma="ὁ" part-of-speech="Pp" morphology="3p---ma--i" head-id="762583" relation="obj" presentation-before=" " presentation-after=" "/>
        <token id="762582" form="δὲ" citation-part="JUDE 1.23" lemma="δέ" part-of-speech="Df" morphology="---------n" head-id="762583" relation="aux" presentation-after=" "/>
        <token id="762583" form="σῴζετε" citation-part="JUDE 1.23" lemma="σῴζω" part-of-speech="V-" morphology="2ppma----i" relation="pred" presentation-after=" "/>
        <token id="762584" form="ἐκ" citation-part="JUDE 1.23" lemma="ἐκ" part-of-speech="R-" morphology="---------n" head-id="762586" relation="obl" presentation-after=" "/>
        <token id="762585" form="πυρὸς" citation-part="JUDE 1.23" lemma="πῦρ" part-of-speech="Nb" morphology="-s---ng--i" head-id="762584" relation="obl" presentation-after=" "/>
        <token id="762586" form="ἁρπάζοντες" citation-part="JUDE 1.23" lemma="ἁρπάζω" part-of-speech="V-" morphology="-pppamn--i" head-id="762583" relation="xadv" presentation-after=", ">
          <slash target-id="762583" relation="xsub"/>
        </token>
      </sentence>
      <sentence id="57048" status="reviewed" presentation-after=" ">
        <token id="762587" form="οὓς" citation-part="JUDE 1.23" lemma="ὁ" part-of-speech="Pp" morphology="3p---ma--i" head-id="762589" relation="obj" presentation-after=" "/>
        <token id="762588" form="δὲ" citation-part="JUDE 1.23" lemma="δέ" part-of-speech="Df" morphology="---------n" head-id="762589" relation="aux" presentation-after=" "/>
        <token id="762589" form="ἐλεᾶτε" citation-part="JUDE 1.23" lemma="ἐλεέω" part-of-speech="V-" morphology="2ppma----i" relation="pred" presentation-after=" "/>
        <token id="762590" form="ἐν" citation-part="JUDE 1.23" lemma="ἐν" part-of-speech="R-" morphology="---------n" head-id="762589" relation="adv" presentation-after=" "/>
        <token id="762591" form="φόβῳ" citation-part="JUDE 1.23" lemma="φόβος" part-of-speech="Nb" morphology="-s---md--i" head-id="762590" relation="obl" presentation-after=", "/>
        <token id="762592" form="μισοῦντες" citation-part="JUDE 1.23" lemma="μισέω" part-of-speech="V-" morphology="-pppamn--i" head-id="762589" relation="xadv" presentation-after=" ">
          <slash target-id="762589" relation="xsub"/>
        </token>
        <token id="762593" form="καὶ" citation-part="JUDE 1.23" lemma="καί#1" part-of-speech="Df" morphology="---------n" head-id="762599" relation="aux" presentation-after=" "/>
        <token id="762594" form="τὸν" citation-part="JUDE 1.23" lemma="ὁ" part-of-speech="S-" morphology="-s---ma--i" head-id="762599" relation="aux" presentation-after=" "/>
        <token id="762595" form="ἀπὸ" citation-part="JUDE 1.23" lemma="ἀπό" part-of-speech="R-" morphology="---------n" head-id="762598" relation="ag" presentation-after=" "/>
        <token id="762596" form="τῆς" citation-part="JUDE 1.23" lemma="ὁ" part-of-speech="S-" morphology="-s---fg--i" head-id="762597" relation="aux" presentation-after=" "/>
        <token id="762597" form="σαρκὸς" citation-part="JUDE 1.23" lemma="σάρξ" part-of-speech="Nb" morphology="-s---fg--i" head-id="762595" relation="obl" presentation-after=" "/>
        <token id="762598" form="ἐσπιλωμένον" citation-part="JUDE 1.23" lemma="σπιλόω" part-of-speech="V-" morphology="-prppma--i" head-id="762599" relation="atr" presentation-after=" "/>
        <token id="762599" form="χιτῶνα" citation-part="JUDE 1.23" lemma="χιτών" part-of-speech="Nb" morphology="-s---ma--i" head-id="762592" relation="obj" presentation-after="."/>
      </sentence>
    </div>
```

**Comment by mlj** [comment] 2017-12-26 22:56
Closing as duplicate of #11. Please continue discussion there.

**Closed by mlj** 2017-12-26 22:56 UTC
